### ISSUE TITLE
"Unable to verify the JWS" exception with a valid signature and key

### ISSUE THREAD

**Issue by nubs** [Spomky-Labs/jose#110]
I'm trying to create a client for [ory-am/hydra](https://github.com/ory-am/hydra) which exposes JWKs for verifying signatures.  I've been able to get code working using node.js, but the equivalent code is not working in PHP.  I've uploaded sample code at https://gist.github.com/nubs/55bea96f606a8c1de08c21cbdb9ae6b0.

The error I get is:
```
PHP Fatal error:  Uncaught exception 'InvalidArgumentException' with message 'Unable to verify the JWS.' in /home/anubis/jose/src/Verifier.php:140
Stack trace:
#0 /home/anubis/jose/src/Verifier.php(62): Jose\Verifier->verifySignatures(Object(Jose\Object\JWS), Object(Jose\Object\JWKSet), NULL, NULL)
#1 /home/anubis/jose/src/Loader.php(114): Jose\Verifier->verifyWithKeySet(Object(Jose\Object\JWS), Object(Jose\Object\JWKSet), NULL, NULL)
#2 /home/anubis/jose/src/Loader.php(49): Jose\Loader->loadAndVerifySignature('eyJhbGciOiJSUzI...', Object(Jose\Object\JWKSet), Array, NULL, NULL)
#3 /home/anubis/jose/test.php(17): Jose\Loader->loadAndVerifySignatureUsingKey('eyJhbGciOiJSUzI...', Object(Jose\Object\JWK), Array)
#4 {main}
  thrown in /home/anubis/jose/src/Verifier.php on line 140
```

Just trying to load the key works (`$loader->load($signature)`), but verifying the signature fails.

I've tried jumping through the code to track down why it didn't work, but I wasn't able to find anything.  Does anything look out of place with what I'm doing?

Thanks for the library!  As long as I can get this working, this will have worked out great for my project.

**Comment by Spomky** [comment]
Thanks for reporting me that bug.
I am trying to find where it comes from as your signature is valid.

Stay tuned.

**Comment by Spomky** [comment]
I found the bug and I am creating a patch to fix it.

Do you allow me to reuse the key and the JWT from your gist above for a test case to avoid futur code regression?

**Comment by nubs** [comment]
Yup - it's a temporary key and fake jwt, so go right ahead.  Thanks!

**Comment by Spomky** [comment]
Tagged `5.0.1`

**Comment by nubs** [comment]
Awesome - thanks.  I'll take a look!

**Comment by nubs** [comment]
It worked fine - thanks for the quick resolution!
