### ISSUE TITLE
slash escaping

### ISSUE THREAD

**Issue by eroux** [Spomky-Labs/jose#118]
I've had difficulties verifying the signature of jws signed with this lib due to a difference in slash escaping with [namshi/jose](https://github.com/namshi/jose). They took care of the issue in [this PR](https://github.com/namshi/jose/pull/41), but I have no idea which behavior is correct and which is not... is it possible to clarify it?

**Comment by Spomky** [comment]
Thank you for reporting me that issue. 
As I understand, you create JWT with that library and try to verify it with namshi/jose. 

This library implements tests based on the RFC7520 and all these tests pass. I am not sure namshi/jose implement those tests.

Plus there is a known bug using ESxxx algorithms. 

In any case, the bug may come from this library. 

Can you indicate which algorithm you are using?
If you have some examples you can share, do not hesitate to send them to me.

**Comment by eroux** [comment]
in fact it's just the opposite: I'm generating JWS with this library and try to read them with namsh/jose, using RS512. I'll try to make a php showing the problem tomorrow.

**Comment by Spomky** [comment]
I made some checks and I am certain the error comes from namshi/jose.
A claim `iat` is added in the payload when it is loaded with `SimpleJWS`. Because this claim is added, the signature becomes invalid for the new payload and causes the error.

There is no error if:
* that `iat` claim is already set in the payload.
* you use `JWS` instead of `SimpleJWS`

**Comment by eroux** [comment]
Ok thanks a lot! As I'm quite sure I would make many mistakes if I do it myself, would you mind reporting the issue on the [namshi/jose tracker](https://github.com/namshi/jose/issues)?

**Comment by Spomky** [comment]
No I will not open an issue. This topic has already been discussed and I gave my POV (see https://github.com/namshi/jose/issues/19#issuecomment-72953334).

That is one of the reasons why I developed that library.

**Comment by eroux** [comment]
It was already reported [here](https://github.com/namshi/jose/issues/44), closing
