### ISSUE TITLE
Missing `createNoneKey`?

### ISSUE THREAD

**Issue by yquan** [Spomky-Labs/jose#122]
When I try to create a "none" key:
```
$none = JWKFactory::createKey(['kty' => 'none']);
```
Throws error:
```
Fatal error: Uncaught Error: Call to undefined method Jose\Factory\JWKFactory::createNoneKey() 
```

Though I know none key is not really signed, but I need it for a purpose (not for verification or signature).

Version:

> spomky-labs/jose                    v5.1.0

**Comment by Spomky** [comment]
Hi,

Thank you for reporting me this issue.
You are right this is a mistake and the method `createNoneKey` should be implemented.

I have just created a PR to fix that issue.
It will be merge and tagged as soon as the tests passed.

BR

**Comment by Spomky** [comment]
Done.

Tagged as `v5.1.1`
