### ISSUE TITLE
Code sample throws exception

### ISSUE THREAD

**Issue by msolomatin-bjss** [Spomky-Labs/jose#134]
Example from https://github.com/Spomky-Labs/jose/blob/master/doc/operation/Verify.md
fails on `$jwk_set = JWKFactory::createFromJKU('https://www.googleapis.com/oauth2/v3/certs');`

```sh
Fatal error: Uncaught exception 'Assert\InvalidArgumentException' with message '
Content type is not "application/json". It is "".' in C:\php\vendor\beberlei\ass
ert\lib\Assert\Assertion.php on line 224

Assert\InvalidArgumentException: Content type is not "application/json". It is "
". in C:\php\vendor\beberlei\assert\lib\Assert\Assertion.php on line 224

Call Stack:
    0.0003     231520   1. {main}() C:\php\TokenVerifyPoC.php:0
    0.1178    1100232   2. Jose\Factory\JWKFactory::createFromJKU() C:\php\Token
VerifyPoC.php:25
    0.1178    1100448   3. Jose\Factory\JWKFactory::getContent() C:\php\vendor\s
pomky-labs\jose\src\Factory\JWKFactory.php:317
    0.1178    1101096   4. Jose\Factory\JWKFactory::downloadContent() C:\php\ven
dor\spomky-labs\jose\src\Factory\JWKFactory.php:369
    0.7514    1469704   5. Assert\Assertion::eq() C:\php\vendor\spomky-labs\jose
\src\Factory\JWKFactory.php:422
```

Environment: WAMP Server 3.0 with php 5.6.16

From http://php.net/manual/en/function.curl-setopt.php:
CURLOPT_SSL_VERIFYPEER is TRUE by default as of cURL 7.10. Default bundle installed as of cURL 7.10

**Comment by Spomky** [comment]
Hi,

I have just fixed that.
Could you try the same code using the last commit.
I expect to release the new major release tomorrow (will be tagged `v6.0.0`).

**Comment by Spomky** [comment]
@msolomatin-bjss can you confirm it works fine on your system?

**Comment by Spomky** [comment]
Tagged `v6.0.0`
