### ISSUE TITLE
Generate JWT for Apple Push Notification

### ISSUE THREAD

**Issue by edamov** [Spomky-Labs/jose#141]
I want to use `jose` library for generating JWT for Apple Push Notification.
But I don't know what implementation (JWT, JWS, JWE, JWA, JWK or JWKSet) I should use.
There are some [requirements](https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/Chapters/APNsProviderAPI.html) for generating this token:
1) Headers should be:
```json
{
    "alg": "ES256",
    "kid": "ABC123DEFG"
}
```
2) Payload data should be:
```json
{
    "iss": "DEF123GHIJ",
    "iat": 1437179036
 }
```
3) APNs supports only provider authentication tokens that are signed with the ES256 algorithm.

So could you please provide an example of generating JWT token for Apple Push Notifications with you library?

**Comment by Spomky** [comment]
What you need is to create a JWS. 
They are some examples in the following folder: https://github.com/Spomky-Labs/jose/tree/master/examples

Normally you should have a private EC key to sign your payload and a public you share with the audience (Apple's  server).

**Comment by Spomky** [comment]
Hi,

I have just vreated a small Gist with the minimal code needed in your case.
See https://gist.github.com/Spomky/246eca6aaeeb7a40f11d3a2d98960282

**Comment by edamov** [comment]
@Spomky you are very welcome!

**Comment by Spomky** [comment]
Closing this issue as the PR #146 is now opened.

**Comment by mpdao** [comment]
@Spomky I followed the steps but I've got the next error:

Fatal error: Uncaught exception 'Assert\InvalidArgumentException' with message 'Signature failed' in /vendor/beberlei/assert/lib/Assert/Assertion.php:260 Stack trace: #0 /vendor/beberlei/assert/lib/Assert/Assertion.php(1526): Assert\Assertion::createException(false, 'Signature faile...', 32, NULL) #1 /Users/CTO/Projects/betlyn-panel/app/classes/vendor/spomky-labs/jose/src/Algorithm/Signature/ECDSA.php(57): Assert\Assertion::true(false, 'Signature faile...') #2 /vendor/spomky-labs/jose/src/Algorithm/Signature/ECDSA.php(40): Jose\Algorithm\Signature\ECDSA->getOpenSSLSignature(Object(Jose\Object\JWK), 'eyJhbGciOiJFUzI...') #3 /vendor/spomky-labs/jose/src/Signer.php(75): Jose\Algorithm\Signature\ECDSA->sign(Object(Jose\Object\JWK), 'eyJhbGciOiJFUzI...') #4 /vendor/spomky-labs/jose/src/Signer.php(53): Jose\Sign in /vendor/beberlei/assert/lib/Assert/Assertion.php on line 260

I have a valid $key_file (from developer.apple.com) and I've checked again kid and iss parameters.

Thanks in advance.
