### ISSUE TITLE
Cannot load minimal private RSA key in JWK format

### ISSUE THREAD

**Issue by jacobkiers** [Spomky-Labs/jose#158]
## Description

When generating a minimal private RSA key in JWK format, the RSAKey class fails to load. This fails to comply with the [RFC section 6.3.2](https://tools.ietf.org/html/rfc7518#section-6.3.2), which states:

    The parameter "d" is REQUIRED for RSA private keys.  The others enable
    optimizations and SHOULD be included by producers of JWKs
    representing RSA private keys.

## Expected behaviour

When importing a minimal RSA Keypair (including only the required `n`, `e` and `d` parameters), the RSAKey should be correctly imported.

## Current behaviour

An exception is thrown with the message:

    The prime "p" is not available.

## Reproduction

The RSA Key is created using [mkjwk.org](https://mkjwk.org). It gives the following output:

```json
{
  "alg": "RS256",
  "d": "JSqz6ijkk3dfdSEA_0iMT_1HeIJ1ft4msZ6qw7_1JSCGQAALeZ1yM0QHO3uX-Jr7HC7v1rGVcwsonAhei2qu3rk-w_iCnRL6QkkMNBnDQycwaWpwGsMBFF-UqstOJNggE4AHX-aDnbd4wbKVvdX7ieehPngbPkHcJFdg_iSZCQNoajz6XfEruyIi7_IFXYEGmH_UyEbQkgNtriZysutgYdolUjo9flUlh20HbuV3NwsPjGyDG4dUMpNpdBpSuRHYKLX6h3FjeLhItBmhBfuL7d-G3EXwKlwfNXXYivqY5NQAkFNrRbvFlc_ARIws3zAfykPDIWGWFiPiN3H-hXMgAQ",
  "e": "AQAB",
  "n": "gVf-iyhwLn2J2Up4EKjwdLYmk5n24gjGk4oQkCHVcE7j8wkS1iSzcu0ApVcMPLklEp_PWycZE12vL90gPeVjF2IPL_MKFL0b6Wy7A1f4kCDkKv7TDDjt1IIwbS-Jdp-2pG7bPb3tWjJUu6QZBLoXfRtW3cMDkQjXaVGixENORLAZs6qdu2MMKV94jetCiFd0JYCjxGVC0HW2OKnM21B_2R1NubOvMlWA7gypdpvmBYDGpkw4mjV3walWlCZObG7IH84Ovl7wOP8XLzqi2un4e6fNzy3rdp4OUSPYItF4ZX5qThWYY2R47Z5sbrZxHjNeDECKUeio0KPQNrgr6FSKSw",
  "kty": "RSA",
  "use": "sig",
  "kid": "test-key"
}
```

In PHP, this fails to load using the following code:

```php
$private_key_json = \json_decode(
    '{
  "alg": "RS256",
  "d": "JSqz6ijkk3dfdSEA_0iMT_1HeIJ1ft4msZ6qw7_1JSCGQAALeZ1yM0QHO3uX-Jr7HC7v1rGVcwsonAhei2qu3rk-w_iCnRL6QkkMNBnDQycwaWpwGsMBFF-UqstOJNggE4AHX-aDnbd4wbKVvdX7ieehPngbPkHcJFdg_iSZCQNoajz6XfEruyIi7_IFXYEGmH_UyEbQkgNtriZysutgYdolUjo9flUlh20HbuV3NwsPjGyDG4dUMpNpdBpSuRHYKLX6h3FjeLhItBmhBfuL7d-G3EXwKlwfNXXYivqY5NQAkFNrRbvFlc_ARIws3zAfykPDIWGWFiPiN3H-hXMgAQ",
  "e": "AQAB",
  "n": "gVf-iyhwLn2J2Up4EKjwdLYmk5n24gjGk4oQkCHVcE7j8wkS1iSzcu0ApVcMPLklEp_PWycZE12vL90gPeVjF2IPL_MKFL0b6Wy7A1f4kCDkKv7TDDjt1IIwbS-Jdp-2pG7bPb3tWjJUu6QZBLoXfRtW3cMDkQjXaVGixENORLAZs6qdu2MMKV94jetCiFd0JYCjxGVC0HW2OKnM21B_2R1NubOvMlWA7gypdpvmBYDGpkw4mjV3walWlCZObG7IH84Ovl7wOP8XLzqi2un4e6fNzy3rdp4OUSPYItF4ZX5qThWYY2R47Z5sbrZxHjNeDECKUeio0KPQNrgr6FSKSw",
  "kty": "RSA",
  "use": "sig",
  "kid": "test-key"
}', true);


$key = new \Jose\KeyConverter\RSAKey($private_key_json);
```

## Possible solution

One solution would be to calculate the `p` and `q` parameters when they are not available. An example algorithm is [on Stackoverflow](http://stackoverflow.com/a/28299742).

I tried to implement that, but I got stuck generating the random integer based on the `n` parameter (step 3a), because I don't have any experience with big integers and the gmp classes.

I'm open to creating a PR for this, if you're willing to help me get through the implementation.

**Comment by jacobkiers** [comment]
It seems I got the implementation working. Apparently, gmp has the required functions to create the required random numbers.

**Comment by Spomky** [comment]
Done.
See [v6.1.4](https://github.com/Spomky-Labs/jose/releases/tag/v6.1.4)

**Comment by Spomky** [comment]
Thanks for your report.
I implemented a solution when I saw your PR.

Now those key are supported, but are not recommended.
You should convert them before.

**Comment by jacobkiers** [comment]
Hi, thank you for picking this up so quickly. I understand that these keys are not ideal.

The nice thing is that once they're first loaded, then the primes are available and the key can be exported again. This should make it a one-time issue.

**Comment by Spomky** [comment]
You are welcome.

In case you missed it, you can easily create a key using the `JWKFactory`. Hereafter an example for a 4096 bits RSA key used for signature with the `RS256` algorithm:

```php
use Jose\Factory\JWKFactory;

$jwk = JWKFactory::createKey([
        'kty'  => 'RSA',
        'size' => 4096,
        'kid'  => 'KEY1',
        'alg'  => 'RS256',
        'use'  => 'sig',
]);
```
