### ISSUE TITLE
Java to Php decode and encode

### ISSUE THREAD

**Issue by paolog22** [Spomky-Labs/jose#160]
hi thanks for this . but i have a problem i am now encountering 

> Token Signature could not be verified.
I generated the Token from SpringBoot and iam trying to decode to Laravel 5.2 Php

thanks :)

**Comment by Spomky** [comment]
Hi,

As Laravel uses another JWT implementation, I am not sure this is the right place for this issue.
Anyway you may try to decode and verify it using that library. Could you share with me test samples?

**Comment by paolog22** [comment]
Java code to generate token
` return Jwts.builder()
                .setClaims(claims)
                .setHeaderParam(TOKEN_HEADER_TYP_KEY,"JWT")
                .signWith(SignatureAlgorithm.HS256, SECRET_KEY)
                .compact();`

After generating the token i am trying to decode it on laravel.
sorry yea i think i post to the wrong place. :) thank for the help man.

**Comment by Spomky** [comment]
You should try to decode it on https://jwt.io/
The interface supports the HS256 algorithm.

**Comment by paolog22** [comment]
yes its all good from jwt.io. Anyway i figured it out man.. thanks laravel is encoding the key to base64 and java is not.

the fix is
from java encode the to base64 then from laravel don't encode :) thanks man

**Comment by Spomky** [comment]
Closing as resolved.
