### ISSUE TITLE
Full Signing and Encrypting Contents Example

### ISSUE THREAD

**Issue by schodemeiss** [Spomky-Labs/jose#162]
Hello,

This library I'm sure works perfectly - once you've got through the fog of the docs :). Much praise for the main developer for that. However... 

The documentation isn't particularly clear on how to create a token that's signed and has encrypted contents.

It'd be great if there was a simple example I could follow to do this? That includes how to generate the keys in the first place, what settings I should use for a standard PHP 7.1 setup, etc.

Cheers,
Schodemeiss

**Comment by xelber** [comment]
Have a look at 
https://github.com/Spomky-Labs/jose/blob/master/examples/NestedTokens.php

**Comment by tm8747a** [comment]
I must agree that the examples are lacking. Obviously understandable given all the other work that went into this, but would definitely be a welcome enhancement, as there's not much point in having a technically great product if people don't know how to use it.  Especially for people who are not well versed in encryption, it's quite hard to figure things out. I'm wrestling right now to figure out how a public/private key scenario would work for encryption and I'm totally at a loss. For example, here's something I tried to encrypt and then decrypt a token:

`<?php

require_once __DIR__ . '/vendor/autoload.php';

use Jose\Factory\JWKFactory;
use Jose\Factory\JWEFactory;
use Jose\Loader;

// We create our loader.
$loader = new Loader();

$key = JWKFactory::createFromKeyFile(
    __DIR__ . '\\public.key',
    null,
    [
        'kid' => 'My Public RSA key',
        'use' => 'enc',
        'alg' => 'RSA-OAEP-256',
    ]
);
// We want to encrypt a very important message
$token = JWEFactory::createJWEToCompactJSON(
    'This is awesome!',
    $key,
    [
        'alg' => 'RSA-OAEP-256',
        'enc' => 'A256CBC-HS512',
        'zip' => 'DEF',
    ]
);

$jwe = $loader->loadAndDecryptUsingKey(
    $token,              // The input to load and decrypt
    $key,              // The symmetric or private key 
    ['RSA-OAEP-256'],           // A list of allowed key encryption algorithms
    ['A256CBC-HS512'],       // A list of allowed content encryption algorithms
    $recipient_index   // If decrypted, this variable will be set with the recipient index used to decrypt
);`

I get an error saying decryption fails, which doesn't surprise me in the least bit as I assume I need a private key, but while I've figured out how to generate some keys, I have no idea how to generate a public/private key pair, which I'm guessing is what I need here? Just an example of the kinds of things people may struggle with.

**Comment by Spomky** [comment]
Hi @tm8747a,

You are right: the documentation is not clear and the examples may confuse people who are not comfortable with those cryptographic operations.
I decided to completely rewrite the documentation with simple use cases and a better explanation on the process. The next major version of this library and the new documentation should be released by the end of the year.
I am also writing a complete course (in French) at https://openclassrooms.com. It will be available in November. I will translate it into English at the beginning of 2018.

To decrypt the tokens created with the example, please read https://github.com/Spomky-Labs/jose/blob/master/examples/Load3.php.

The easiest way to create a RSA key is using the JWKFactory:

```php
use Jose\Factory\JWKFactory;

$private_key = JWKFactory::createKey([ 'kty'  => 'RSA', 'size' => 4096]);
```

The result of this call will give you a private RSA key. To get the associated public key, just call the method `toPublic()`:


```php
use Jose\Factory\JWKFactory;

$public_key = $private_key->toPublic();
```

The public key can be shared and used to encrypt.
The private key is used to decrypt the tokens you will receive.

**Comment by tm8747a** [comment]
Thanks for the quick reply! That's what I needed, looking forward to the new docs. Luckily for me I do speak French so I guess I can check out the course once it's available.

**Comment by Spomky** [comment]
Closing as answered.
