### ISSUE TITLE
Allow "simple" JWEs to be loaded using the JWTLoader.

### ISSUE THREAD

**Issue by lemoinem** [Spomky-Labs/jose#171]
I'm trying to load a JWE, that I created using `JWTCreator::encrypt()`.

Unfortunately, `JWTLoader->load()` seems to always expect a base64 JWS as the JWE payload.

I actually don't need the additional encapsulation (JWE already sign its public headers and I really don't need to encrypt my signature, as the point is that my private claims are in the encrypted payload).

In the same way that the JWTLoader can load a bare JWS (not encapsulated in a JWE), 
I think we should change `JWTLoader::load()` to return a JWT instead of a JWS, similarly, `JWTLoader::verify()` should accept JWT.

I'm not sure whether we should perform the signature (tag) verification for JWEs in `verify()`, since it should have already been done during the decryption phase.

I understand this would be a BC-break since we are widening the return type of a method, but we could be provide a new method `JWTLoaderInterface::loadJWE()` to avoid the BC-break and merge them back in the next major version.

What do you think?

I'm ready to provide a PR if you like the idea.

**Comment by Spomky** [comment]
Hi @lemoinem.
You are right, the `JWTLoader->load()` method is a convenient way to load JWS or nested JWS (i.e. a JWS in a JWE). If you pass a JWE that does not contain any JWS (e.g. a simple message), then the method will throw an exception.

I am working on the next major release. Lot of changes is planned and the JWTLoader/JWTCreator classes will also be modified. Any BC Break spotted here could be included in this next version.
At the moment and to solve this issue, I recommend you to use the `Loader` class and `loadAndDecryptUsingKey` or `loadAndDecryptUsingKeySet` methods:

```php
use Jose\Loader;

$jwe = $loader->loadAndDecryptUsingKey(
    $input,            //Your JWE (string)
    $key,              // Your private decryption key (JWK)
    ['RSA-OAEP-256'],  // A list of allowed key encryption algorithms
    ['A256CBC-HS512'], // A list of allowed contentencryption algorithms
    $recipientIndex    // If the JWE contains several recipient, the index indicates the one used to decrypt the token
);
```

The method `verify` only allows a JWS to be passed because verifying a JWE is irrelevant to me. A JWE can be produced by any party with a public key, then you cannot trust its content unless it it a signed content (nested JWT).

**Comment by lemoinem** [comment]
Thank you for the answer and the suggestion of using the Loader's method directly.

Regarding verifying a JWE, I think there are two points that could still make sense:

1. When using symmetric encryption (in my particular case, AES-GCM), there are no public key, and therefore not "any party" could create the JWE. In this case having the unencrypted part (Shared Protected Headers / AAD) could still be part of the verification process. Although, I think that might be taken care of during the decryption step.

2. Most importantly, the current implementation of `JWTLoader->verify()` also performs the claims' check. Which, I think, is relevant even for JWEs.

In any case you've created a great library and bundle and I'm looking forward to V7. If you would like help on this issue, I'm more than ready to contribute a PR.

**Comment by Spomky** [comment]
> When using symmetric encryption (in my particular case, AES-GCM), there are no public key, and therefore not "any party" could create the JWE. In this case having the unencrypted part (Shared Protected Headers / AAD) could still be part of the verification process. Although, I think that might be taken care of during the decryption step.

Exact. However the shared protected header and the AAD are already checked by the library during the decryption process: see the [this method](https://github.com/Spomky-Labs/jose/blob/master/src/Algorithm/ContentEncryption/AESCBCHS.php#L47) for the AES-CBC-HMAC-SHA2 algorithms. For AES-GCM, the authentication tag is computed by the algorithm itself.
A double check is not needed.

> Most importantly, the current implementation of JWTLoader->verify() also performs the claims' check. Which, I think, is relevant even for JWEs.

I agree with you. The verification of the decrypted ciphertext could be added. I will modify the library accordingly.

**Comment by lemoinem** [comment]
Thank you for your answers! Looking forward to V7! :)

**Comment by Spomky** [comment]
Hi @lemoinem 

This issue is now fixed on the [V7 branch](https://github.com/Spomky-Labs/jose/tree/v7).
You will be able to load, decrypt and check claims of an encrypted token.

I let this issue opened until the new major version is released.

**Comment by Spomky** [comment]
Closing as answered.
