### ISSUE TITLE
integrate react native with jose

### ISSUE THREAD

**Issue by assafb81** [Spomky-Labs/jose#211]
Hi,
I write an application that receives data in JSON format and I want to validate the data source before the application starts to process the data.
currently the data is stored in Amazon and the application is written in React Native (version 0.45.1).

I wonder: 
1. Is it possible to integrate jose package with react native?
2. If yes, how?
3. In the 1st stage I will have static data in Amazon, so I wonder how I can sign the data with jose

Thanks

**Comment by Spomky** [comment]
Hi,

On client side, it looks difficult to integrate this library in your application as it is writtent in PHP and your application is in JS.
I found [a nice blog post where tokens are used](https://auth0.com/blog/adding-authentication-to-react-native-using-jwt/). It may help you to validate those signatures in your react native application.

I do not use Amazon services, however if you can run PHP applications on their servers, then you will be able to sign your data with this library.

**Comment by assafb81** [comment]
As I understand from the article the validation is done using 'tcomb-form-native' library which works on forms, and it only validate that the data is in the expected type and not the value.
The tokens are used to perform authorization, this is an issue that currently I don't need to address.

I need to validate if the data arrived from the source I expect, to prevent Man In the Middle Attack.

**Comment by Spomky** [comment]
I am sorry I misunderstood your need.
So I think you could directly use [jsrsasign](http://kjur.github.com/jsrsasign) to verify the tokens from your application (see http://kjur.github.io/jsrsasign/slide_e/#/11 for an example of verification).

**Comment by assafb81** [comment]
Thanks, I am already trying to use jsrsasign..hopefully it will work

**Comment by Spomky** [comment]
Closing as I do not think this library will help you (JS application).
Feel free to reopen it if you think so.
