### ISSUE TITLE
Call to undefined function Jose\Util\gmp_init()

### ISSUE THREAD

**Issue by michaelchemani** [Spomky-Labs/jose#218]
Got `Call to undefined function Jose\Util\gmp_init()` when trying to encrypt (JWE) a JWT.

gmp is installed correctly.

Any idea?

**Comment by Spomky** [comment]
Hi,

Can you tell me where the error occurred (file/line)?

**Comment by michaelchemani** [comment]
Sure, `Error [1]: Call to undefined function Jose\Util\gmp_init() in /web/cloud/vendor/spomky-labs/jose/src/Util/BigInteger.php on line 39`

**Comment by Spomky** [comment]
Thanks.

Does this error come from the CLI or from your web application?

You mentioned that the extension is correctly installed and I am pretty sure it is.
If it comes from your web app, my understanding is that the extension is correctly installed on you CLI configuration, but not on your web one.
On Debian/Ubuntu servers, you will find that configuration in the folder `/etc/php/{PHP_VERSION}/{apache2 or fpm}/php.ini`

**Comment by Spomky** [comment]
You have to find the location of the `php.ini` file.
Create a web page: 

```php
<?php

phpinfo();
```

Check if the gmp module is available and where the php.ini is.
If the module is not available, then just add `extension=php_gmp.so` or `extension=gmp.so`

**Comment by Spomky** [comment]
Closing as not related to the library but to the environment.

**Comment by juanm18** [comment]
@Spomky I am running into this same issue. I have GMP installed and included it in my `php.ini` file. I am trying to create an RSAKey pair like so:
`$private_key = JWKFactory::createRSAKey(
    4096, // Size in bits of the key. We recommend at least 2048 bits.
    [
        'alg' => 'RSA-OAEP-256', // This key must only be used with the RSA-OAEP-256 algorithm
        'use' => 'enc',    // This key is used for encryption/decryption operations only
    ]);`

Then building my JWE like this:
`$jwe = $jweBuilder->create()->withPayload($payload)->withSharedProtectedHeader(['alg' => 'RSA-OAEP-256', 'enc' => 'A256CBC-HS512',])->addRecipient($public_key)->build();`

If i run your example provided in the documentation for building a `JWE` i do not get the error but when building a different Key then i run into the error. Any ideas of what may be the issue?

Error:
`Fatal error: Uncaught Error: Call to undefined function gmp_init() in /Volumes/Source/authserver/vendor/web-token/jwt-core/Util/BigInteger.php:47
Stack trace:
#0 /Volumes/Source/authserver/vendor/web-token/jwt-core/Util/RSAKey.php(213): Jose\Component\Core\Util\BigInteger::createFromBinaryString('0xd4b03a1d0e2b4...')
#1 /Volumes/Source/authserver/vendor/web-token/jwt-core/Util/RSAKey.php(188): Jose\Component\Core\Util\RSAKey->convertBase64StringToBigInteger('1LA6HQ4rQ3q1b20...')
#2 /Volumes/Source/authserver/vendor/web-token/jwt-core/Util/RSAKey.php(83): Jose\Component\Core\Util\RSAKey->populateBigIntegers()
#3 /Volumes/Source/authserver/vendor/web-token/jwt-core/Util/RSAKey.php(92): Jose\Component\Core\Util\RSAKey->__construct(Object(Jose\Component\Core\JWK))
#4 /Volumes/Source/authserver/vendor/web-token/jwt-encryption-algorithm-rsa/RSA.php(30): Jose\Component\Core\Util\RSAKey::createFromJWK(Object(Jose\Component\Core\JWK))
#5 /Volumes/Source/authserver/vendor/web-token/jwt-encryption/JWEBuilder.php(366): Jose\Component in /Volumes/Source/authserver/vendor/web-token/jwt-core/Util/BigInteger.php on line 47`

**Comment by moderndeveloperllc** [comment]
@juanm18 What is the output of `php --ri gmp`? Also, I think @Spomky is focusing on https://github.com/web-token/jwt-framework as the replacement for this lib. Not sure he is doing much more than security fixes on this now.

**Comment by juanm18** [comment]
Sorry i totally overlooked the repo name but i am using the `jwt-framework` library. As for your question, this is what i get 
`gmp

gmp support => enabled
GMP version => 6.1.2`  @moderndeveloperllc
