### ISSUE TITLE
Disable `None` by default

### ISSUE THREAD

**Issue by odino** [Spomky-Labs/jose#25]
One of the things I would recommend is to either disable `none` by default.

It [created a lot of problems](https://auth0.com/blog/2015/03/31/critical-vulnerabilities-in-json-web-token-libraries/) and it has been proven that leaving this checks to the user can really hurt :)

So I would suggest that whoever wants to use none, should specifically enable it.

Cheers!

**Comment by Spomky** [comment]
Hi,

This library only provides encryption/signaturealgorithms, but no algorithm is loaded by the algorithm manager.
Applications that use this library must explicitly enable algorithms: Each application is responsible of algorithms used. I added a message [on this page](https://github.com/Spomky-Labs/jose/blob/master/doc/Status.md) to warn developers the `none` algorithm is not secured.

```php
$key_manager = new JWAManager();
$key_manager->addAlgorithm(new HS256())
    ->addAlgorithm(new HS384())
    ->addAlgorithm(new HS512())
    ->addAlgorithm(new RS256())
    ->addAlgorithm(new RS384())
    ->addAlgorithm(new RS512())
    ->addAlgorithm(new PS256())
    ->addAlgorithm(new PS384())
    ->addAlgorithm(new PS512())
    ->addAlgorithm(new ES256())
    ->addAlgorithm(new ES384())
    ->addAlgorithm(new ES512())
```
