### ISSUE TITLE
Rotatable key set missing documented rotation period argument

### ISSUE THREAD

**Issue by mdeboer** [Spomky-Labs/jose#290]
Version used: `v6.1.5`

The [documentation](https://github.com/Spomky-Labs/jose/blob/v6.1.5/doc/object/jwkset.md#create-a-rotatable-key-set) states that `Jose\Object\RotatableJWKSet` or at least its factory method `JWKFactory::createRotatableKeySet` can take a fourth argument stating the period at which keys should rotate. However, this fourth argument is missing from both the class and factory method nor is `rotate()` called anywhere.

**Comment by Spomky** [comment]
Hi,

It looks like it is a mistake in the documentation.
The rotate command rotates the key set at each call.

If you want to rotate it after a period, you have to compare the last modification date, the current time and the period.

Example:

```php
$ttl = 3600 * 24 * 7; // 7 days
$mtime = $jwkset->getLastModificationTime(); // $jwkset is your RotatableJWKSet object

if (null === $mtime) { // $mtime may be null if the key set does not exist.
    $service->regen();
} elseif ($mtime + $ttl <= time()) {
    $service->rotate();
}
```

I will update the documentation or add a new method to handle that.

**Comment by mdeboer** [comment]
Thanks @Spomky, no worries I'm working on a PR right now and almost done. Would you mind to take a look at it later? I made the rotation interval optional so it won't break existing code.

Thanks for your quick reply, really need this function 👍

**Comment by mdeboer** [comment]
See #292 for my PR 👍
