### ISSUE TITLE
Use local linting configuration instead of depending on CI

### ISSUE THREAD

**Issue by mdeboer** [Spomky-Labs/jose#296]
I suggest to use local PHPCS/PHPMD configuration files so you can lint locally in your IDE and be sure that when you commit, you don't have to follow up with a commit to fix those issues.

Unlike what it says in the contributing guide, more standards are followed than simply PSR-1 and PSR-2 because neither of them require a "." after docblock comments for example. This is fine but it would help to know which standards are followed in addition to PSR-2.

**Comment by Spomky** [comment]
I think you are right.
At the moment I use https://styleci.io/ and its default configuration to automate the CS review.
A local application with clear rules would be more appropriate.

**Comment by Spomky** [comment]
Closing as styleci.io is not used anymore
