### ISSUE TITLE
Can't figure out how to use A128CBC-HS256 algorithm

### ISSUE THREAD

**Issue by tm8747a** [Spomky-Labs/jose#304]
I'm trying to encrypt using the A128CBC-HS256, but I can't figure out what key to use. I've tried a bunch of different ones listed under "Supported Key Encryption Algorithms" and keep getting errors for all of them. Any pointers?

**Comment by Spomky** [comment]
Hi,

To create an encrypted token, you need two algorithms:
* Key encryption algorithm
* Content encryption algorithm (A128CBC-HS256 in your case)

The key used by the content encryption algorithm depends on the key encryption algorithm.

You will find a [small example here](https://github.com/Spomky-Labs/jose/blob/master/examples/Encrypt1.php). It uses the A256CBC-HS512 algorithm, but the computation is identical.

**Comment by tm8747a** [comment]
Thanks for the quick reply. It was actually a problem on my end that had me thinking I had the wrong key type. The key given to me wasn't properly encoded and I hadn't noticed. It's now working as expected. Thanks again!
