### ISSUE TITLE
Add detailed exception for Claims check

### ISSUE THREAD

**Issue by achretien** [Spomky-Labs/jose#305]
I tried to create an issue on your new repo without success.

Could it be possible to add exception like AudienceException or ExpiryException so ti will be easier to handle them in the code later?

Thanks

**Comment by Spomky** [comment]
Hi,

This is a nice feature but now this library only receives security fixes and will be abandonned by the end of 2019 (see #297).
 I will not add it here, but it is already incorporated in my local repository of [the next project](https://github.com/web-token). This new project will be marked as stable in December.

**Comment by Spomky** [comment]
Done in https://travis-ci.org/web-token
