### ISSUE TITLE
Better DownloadedJWKSet error informarion

### ISSUE THREAD

**Issue by fkupper** [Spomky-Labs/jose#312]
### DownloadedJWKSet.php exception message

When getting a key set from an URL, having just `'Unable to get content.'` as a clue of what is the problem is not that helpful. 

Related class code:
https://github.com/Spomky-Labs/jose/blob/master/src/Object/DownloadedJWKSet.php#L142

It would be interesting to:

- Get a better message from exception with curl error information, taking in consideration not exposing sensitive information.
- Log curl errors.

### Jose\Loader::loadAndVerifySignatureUsingKeySet*

Also related to the same issue, when a JWKSet is created from URL and passed as parameter to `Jose\Loader::loadAndVerifySignatureUsingKeySet*`, if `DownloadedJWKSet.php` fails as explained before. I get a generic `'Unable to get content.'` again which is very unclear where it failed to get contents from and why. 

It would help to have a different type of exception, better error message, exception code or something that could identify what was the problem. 

To be able to identify this beforehand, I have to use a sort of hack:

``` php
public function getKeySet() 
{
    $jwkSet = JWKFactory::createFromJKU(
        'http://some.public.key/set'
    );
    // triggers
    // https://github.com/Spomky-Labs/jose/blob/master/src/Object/DownloadedJWKSet.php#L142
    // so I can at least know at what moment the exception came at
    $keys = $jwkSet->getKeys();
    // recreates the JWKSet to
    $keysValues = array_map(
        function (JWK $key) {
            return $key->getAll();
        },
        $keys
    );
    return new JWKSet(['keys' => $keysValues]);
}
```
I am open to help with this.

**Comment by fkupper** [comment]
@Spomky I have a pull request for this. (at least part of this)

**Comment by Spomky** [comment]
Hi @fkupper,

Thanks for the PR. I will review it tomorrow.
It looks good however I noticed that you throw a RuntimexException instead of an InvalidArgumentException.
You are right, bu by changing the exception type you create a BC break. applications that catch the InvalidArgumentException may not work correctly.

**Comment by fkupper** [comment]
You're right, I will have a look and fix it.
The reason why I did it like this is only so I could have different exception types for different types of failures. But you're right.

**Comment by fkupper** [comment]
Fixed it.

**Comment by fkupper** [comment]
@spomky up

**Comment by Spomky** [comment]
Closing as merged.
Thanks.
