### ISSUE TITLE
Example code for a loader?

### ISSUE THREAD

**Issue by jcwatson11** [Spomky-Labs/jose#32]
Hello,

First, thanks for your work on this project. It looks very promising, and I do look forward to it reaching maturity. Of all the PHP/JOSE projects out there, this one seems to be thought out the best, and *claims* to support the most diverse set of algorithms, especially A256GCM, which is the one I need. None of the others do that. I'm glad you've found a way.

I would like to see this project gain some popularity in the long run, so here are some ideas about how it could begin to gain momentum:

First, please provide more examples for specific cases.

For example, I have been tasked with decrypting a A256GCM JWE payload with a shared private key. My first step was to read your documentation, which provides no direction on how to create the $loader object for such a case (unless I missed it). The docs presume that you know what a $loader is, and where it came from, how to create one, etc. When I look at your test cases, the complexity of creating a loader only increases exponentially.

Second, why is there a need for the implementer to create their own implementation of a loader and a key manager? It appears, since you have an implementation of a loader in the tests themselves, that the consumer of your library is supposed to implement the abstract Loader class outside of your library. Is that right? If so, that might be good for covering your rear as a security provider (which is irrelevant for something published under the MIT license anyway), but it's really bad for getting people interested in using your code.

From my perspective, and in my case, I would expect to provide four simple things to a JWE library:

The information I have is:

1. My private shared key.
2. The name of the encryption algorithm.
3. The fact that I expect the signature to claim that it is of type 'dir'.
4. The JWE string itself, which has 5 segments separated by dots.

Given that above information, I would imagine a smart library would be able to figure out what classes it needs to load, do the decryption, and simply give me an object back that represents the decrypted payload.

However, with this library as it stands now, I'm afraid I would have to implement my own loader, key manager and ... well, I didn't even look at what else, because it's too much for me to get in to. I may as well roll my own quick and dirty decryption to unwrap the JWE instead of using a library that makes me write several classes anyway, and provides no coaching on how to do that.

Again, I really like the direction you're going with the organization of the code. It's just incomplete. Maybe you were going to get to that eventually, and if so, then I'm cheering you on, and you can just say, "Yeah, I was getting to all of that."

Does that make sense?

**Comment by Spomky** [comment]
Hi,

Thank you for your words of encouragement.

I know this library is not easy to use as almost all classes are abstract and the documentation is not written.
I will write the documentation when this library will reach maturity, all bugs are fixed and tests cover all main functionnalities (see [v1.0.0 milestone](https://github.com/Spomky-Labs/jose/milestones)).

Abstract classes are quite disturbing for developpers because I would like this library to fit on any type of frameworks. I updated these classes and added setters, getters and other missing methods. It should be better now.

Anyway, I would like recommend you and (other developers) to use another project based on this library: [jose-service](https://github.com/Spomky-Labs/jose-service).
This project is under developement, but you will see it is easier to use ([thanks to Pimple](http://pimple.sensiolabs.org/)).
I added examples to demonstrate how to create JWS, JWE, JWS+JWE and load your all of these encrypted/signed data.

Regards

**Comment by Spomky** [comment]
Hi,

I created [a small example](https://gist.github.com/Spomky/de287de15f19baab599b) to demonstrate how to load a JWE using A256GCM and dir algorithms.

Just create the files, run `composer install` and execute the example `php example.php`.

**Comment by Spomky** [comment]
Hi @jcwatson11,

I added some examples to help you to signn, encrypt and load JWT.
Especially, I created [an example](https://github.com/Spomky-Labs/jose/blob/master/examples/Load4.php) using a direct key and A256GCM algorithm.

Tell me if you need more information.

**Comment by Spomky** [comment]
Hi,

I created a new branch that simplifies the signature/encryption/verification/decryption of JWT.
Now, you will be able to decrypt a JWE with only few lines of code:

```php
<?php

require_once __DIR__.'/vendor/autoload.php';

use Jose\Factory\DecrypterFactory;
use Jose\Factory\JWKFactory;
use Jose\Loader;
use Jose\Object\JWEInterface;

$shared_key = JWKFactory::createFromValues([
    'kty' => 'dir',
    'dir' => 'saH0gFSP4XM_tAP_a5rU9ooHbltwLiJpL4LLLnrqQPw',
]);

$input = 'eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIiwia2lkIjoiTXkgU2hhcmVkIEtleSJ9..gqkq-9muWfQd3AHD.kg_fCtrkId7poGRCUP9ARO4KQ4m0R6lU5rwNS8Mm8nLFMy_X3nBC1VkL_zDehO4K6eEliZ9ISBEE7fFM6aFppfTCwFd_q-qikoOy7zsSeOOEawDZX2qMMdZYnaZs1HZTezdgS7HmoNK1J1TfE1PNrmhjrIZEbTANWw.Hxy5fTBX8X10_bz5UuDeBQ';

$jwe = Loader::load($input);

if (!$jwe instanceof JWEInterface) {
    throw new \RuntimeException('Something went wrong');
}
$decrypter = DecrypterFactory::createDecrypter(
    [
        'dir',
        'A256GCM',
    ]
);

$is_decrypted = $decrypter->decryptUsingKey($jwe, $shared_key);

```

I let this issue opened. I will close it when the new documentation is written.

**Comment by Spomky** [comment]
Examples and docuementation updated.

**Comment by m1ch3lp3r3z** [comment]
Hi, I'm trying to use this library the simplest way possible with just a shared key or phrase "secret" and maybe the HS512 alg, but I failed to find a sample or in the code somewhere that suggested this can be done. Is there a way?, I noticed key type "dir" is not supported anymore?, just:
`'RSA' => 'RSA', 'OKP' => 'OKP', 'EC' => 'EC', 'oct' => 'Oct', 'none' => 'None'`

Thanks!!

**Comment by Spomky** [comment]
A passphrase is just an octet key (`oct`). The passphrase is base 64 url safe encoded .

```php
use Jose\Object\JWK;
use Base64Url\Base64Url;

$passphrase = 'This is my secured passphrase';

$key = new JWK([
    'kty' => 'oct',
    'k'   => Base64Url::encode($passphrase),
    'use' => 'sig',
]);
```

**Comment by jcwatson11** [comment]
Wow! It's been a while since I posted this question and it looks like the package maintainer has come through like a super star. @m1ch3lp3r3z I'm sure you're in good hands, as @Spomky seems to be very responsive (unlike me).

In our case, we ended up choosing not to use JWE for our project and instead opted for no encryption (JWT) instead. I believe we still do use this package in an earlier version (we have not upgraded to PHP 5.6 yet), just not for encrypted tokens. Therefore this question was no longer relevant to me. However, I am so very glad it ended up useful for everyone else. I just took some time and reviewed the project and all the work you've done. I love the direction you're headed!

Thanks for your work @Spomky !

**Comment by m1ch3lp3r3z** [comment]
Thank you @Spomky @jcwatson11 !! Maybe that sample can be included in the docs.

**Comment by Spomky** [comment]
@m1ch3lp3r3z you are right the documentation has to cover JWK creation from passphrase. Same goes for the `dir` keys (those keys are supported but the doc is not really clear). I will update it ASAP.

@jcwatson11 the package evolved a lot since Aug. 2015. I am happy to see that it is now used by developers. I keep in mind your first words and I am trying to offer a seamless user experience even for the encryption process.
If you can upgrade PHP, then you should consider PHP 7.1 instead of PHP 5.6. You will get better results especially if you want to use a GCM based algorithm.
