### ISSUE TITLE
Add basic Auth header to createFromJKU

### ISSUE THREAD

**Issue by oadekoya12** [Spomky-Labs/jose#321]
Hi
How can i add basic auth to "JWKFactory::createFromJKU('URL');".

For example:
`$username = "some-username";
$password = "some-password";
$remote_url = 'http://www.somedomain.com/path/to/file';

// Create a stream
$opts = array(
  'http'=>array(
    'method'=>"GET",
    'header' => "Authorization: Basic " . base64_encode("$username:$password")                 
  )
);

$context = stream_context_create($opts);

// Open the file using the HTTP headers set above
$file = file_get_contents($remote_url, false, $context);`

Thanks
Olawale

**Comment by Spomky** [comment]
Hi,

This is a nice feature. Just let me few days to add it, test it and tag it.
I think I will add an option (array) to the `createFromJKU` method.

**Comment by Spomky** [comment]
Hi,

Can you please check if it works correctly with the branch `CustomHttpHeaders`?
I will add tests soon. Then merge if everything is fine.
Will be tagged 7.1.0 as some method signatures changed.
