### ISSUE TITLE
Cannot pass signature verification

### ISSUE THREAD

**Issue by oadekoya12** [Spomky-Labs/jose#322]
Hi
I am trying to verify a public JWK on a token with an error.

> invalidArgumentException: Unable to verify the JWS. in Jose\Verifier->verifySignatures() (line 146 of .../spomky-labs/jose/src/Verifier.php).

Code:
`  $remote_key = [{"keys":[{"kty":"RSA","e":"....","n":"....","kid":"...."}]}];
    $key_remote_json = json_decode($remote_key, true);
    $new_key_set = new Jose\Object\JWKSet($remote_key_json);

    // We create our loader.
    $loader = new Jose\Loader();
    $jws = $loader->loadAndVerifySignatureUsingKeySet(
      $jwt_remote,
      $new_key_set,
      ['RS256'],
      $signature_index
    );
`
Thanks
Olawale Adekoya

**Comment by Spomky** [comment]
Hi,

It is hard to say where the error comes from, some verifications can be done.

* Check if your token do really use the algorithm `RS256`,
* Does the key set contains the correct public key?
* Is your token encrypted? In this case it has to be decrypted first.

If possible, can you send me a sample and the associated public key set?

**Comment by oadekoya12** [comment]
Hi,
I try to verify the output of "$new_key_set->toPEM()" convert at jwt.io site and it worked.
I don't know what is going on.

Thanks
Olawale Adekoya

**Comment by oadekoya12** [comment]
The "print_r($new_key_set->getKeys()[0]);" ...result

`Jose\Object\JWK Object ( [values:Jose\Object\JWK:private] => Array ( 
    [kty] => RSA 
    [e] => AQAB 
    [n] => 1xO2XltKyUeIoKTx2I_Nu_uOfVtyRnKUzwrmq30PFfbv1CfeYQQcMzXIodkurSNdOUq5PBBzvodHkmO... 
    [kid] => MM0rZipWMqz2NPCL... ) ) `

Thanks

**Comment by oadekoya12** [comment]
For some reason, I cannot get out of the verification state at Verifier.php.
I don't know what am doing wrong.
`    private function verifySignatures(Object\JWSInterface $jws, Object\JWKSetInterface $jwk_set, $detached_payload = null, &$recipient_index = null)
    {
        $this->checkPayload($jws, $detached_payload);
        $this->checkJWKSet($jwk_set);
        $this->checkSignatures($jws);

        $nb_signatures = $jws->countSignatures();
       
        for ($i = 0; $i < $nb_signatures; ++$i) {
            
            $result = $this->verifySignature($jws, $jwk_set, $signature, $detached_payload);
            dsm($result);   **// it's empty**

            if (true === $result) {
                $recipient_index = $i;

                return;
            }
        }

        throw new \InvalidArgumentException('Unable to verify the JWS.');
    }`

**Comment by oadekoya12** [comment]
Thanks for the help via chat, Spomky.
For anybody that's having a problem with verification, these are my steps:
**Using Public Key for verification**
`//Add PEM key from file
    $jwk_public_pem = JWKFactory::createFromKeyFile('/path/to/the/public/file.pem', 'secret', ['use' => 'sig', 'alg'=> 'RS256']);

    //Set JWK version of the PEM
    $jwkset_public = new JWKSet();
    $jwkset_public->addKey($jwk_public_pem);

    $loader = new Loader();

    $jws = $loader->loadAndVerifySignatureUsingKeySet(
        $id_token,
        $jwkset_public,
        ['RS256'],
        $signature_index
  );
return $jws->getPayload();`

**Using JWK for verification**
`//keys in array
    $key_remote_json = json_decode($jwk, true);
    $key_remote_json = $key_remote_json['keys'][0];

    //convert to public
    $key = new Jose\KeyConverter\RSAKey($key_remote_json);
    $pem = $key->toPEM();
    $jwk = JWKFactory::createFromKey($pem);

    $jwkset = new JWKSet();
    $jwkset->addKey($jwk);
    $loader = new Loader();

    $jws = $loader->loadAndVerifySignatureUsingKeySet(
        $id_token,
        $jwkset,
        ['RS256'],
        $signature_index
    );
    return $jws->getPayload();`

Again, Thanks Spomky.
