### ISSUE TITLE
Trying to generate the same key between two APIs

### ISSUE THREAD

**Issue by z3nth10n** [Spomky-Labs/jose#326]
Well, my question is simple, I already do it on Stackoverflow:

https://stackoverflow.com/questions/50263796/generate-the-same-jose-token-between-client-and-server-php-c

Can someone guide me? Thanks.

**Comment by Spomky** [comment]
Hi,

First, it is normal to have different tokens eve if you have the same payload or encryption keys.
It is needed to avoid known attacks.

It looks like the error comes from the keys you use. Can you send me the private and public keys?

**Comment by Spomky** [comment]
By the way, Felippe Duarte is right and the key loading can be simplified:

```php
use Jose\Factory\JWKFactory;

$file = __DIR__ . '/../keys/public.key'; // or __DIR__ . '/../keys/private.key'
$key = JWKFactory::createFromKeyFile($file);
```

**Comment by z3nth10n** [comment]
Thanks for your answer, I though I would never be answered.

Those are my keys.

[private.txt](https://github.com/Spomky-Labs/jose/files/1991533/private.txt)
[public.txt](https://github.com/Spomky-Labs/jose/files/1991534/public.txt)

I know Felippe Duarte is right cause he said that the way do it is wrong, I know, I only testing posibilities with your API. Now, I will try testing what you said:

`JWKFactory::createFromKeyFile($file);`

Thanks so much.

**Comment by z3nth10n** [comment]
Another question is [@dvsekhvalnov](https://github.com/dvsekhvalnov) is suggesting me to remove Deflate compression from the API, this is possible in the PHP API?

I'm looking in the code, and it seems like Encryptation is an ingrained feature:

    private static function createJWEAndEncrypt($payload, JWKInterface $recipient_key, array $shared_protected_headers = [], $shared_headers = [], $recipient_headers = [], $aad = null)
    {
        $complete_headers = array_merge($shared_protected_headers, $shared_headers, $recipient_headers);
        Assertion::keyExists($complete_headers, 'alg', 'No "alg" parameter set in the header');
        Assertion::keyExists($complete_headers, 'enc', 'No "enc" parameter set in the header');
        $encrypter = Encrypter::createEncrypter([$complete_headers['alg']], [$complete_headers['enc']], ['DEF', 'ZLIB', 'GZ']);

        $jwe = self::createJWE($payload, $shared_protected_headers, $shared_headers, $aad);

        $jwe = $jwe->addRecipientInformation($recipient_key, $recipient_headers);

        $encrypter->encrypt($jwe);

        return $jwe;
    }

I will look deeper. But I will suggest that implementing the possibility of disabling compression will be a good think. I don't know yet if this is possible, and I will edit my own posts as I discover new things.

**Comment by z3nth10n** [comment]
Another issue is that keys generated from PHP (JWKFactory) can't be loaded from C# and tokens generated with C# keys (that comes from phpseclib in PHP) can't be readed because of the following fact:

http://php.net/manual/fr/function.openssl-pkey-get-public.php#101513

"If you are trying to read a PKCS#1 RSA public key you run into trouble, because openssl wants the public key in X.509 style."

openssl_pkey_get_public expects a different format, but I don't know how can I export it to PKCS (that is the format that the C# part expects also) in your API. Thats the reason why I have weird implementation `$jwk = new \Jose\KeyConverter\RSAKey($contents);` & `new \Jose\Object\JWK($jwk->toArray()),`.

I will trying...

**Comment by z3nth10n** [comment]
Thanks for your long response and for answering all my questions.

I tried to decompiled your key, but as [I said here](https://github.com/dvsekhvalnov/jose-jwt/issues/93#issuecomment-388213496) my method of importing fails. I will do what @dvsekhvalnov said me, or at least try to fix the existing method.

**Comment by dvsekhvalnov** [comment]
Hi @Spomky, as an exercise i decoded reference example you posted. It decoded succesfully. 
Here is C# code just for reference (sorry to pollute your project space):

```c#
            string json = @"
{
    ""n"": ""wbdxI55VaanZXPY29Lg5hdmv2XhvqAhoxUkanfzf2-5zVUxa6prHRrI4pP1AhoqJRlZfYtWWd5mmHRG2pAHIlh0ySJ9wi0BioZBl1XP2e-C-FyXJGcTy0HdKQWlrfhTm42EW7Vv04r4gfao6uxjLGwfpGrZLarohiWCPnkNrg71S2CuNZSQBIPGjXfkmIy2tl_VWgGnL22GplyXj5YlBLdxXp3XeStsqo571utNfoUTU8E4qdzJ3U1DItoVkPGsMwlmmnJiwA7sXRItBCivR4M5qnZtdw-7v4WuR4779ubDuJ5nalMv2S66-RPcnFAzWSKxtBDnFJJDGIUe7Tzizjg1nms0Xq_yPub_UOlWn0ec85FCft1hACpWG8schrOBeNqHBODFskYpUc2LC5JA2TaPF2dA67dg1TTsC_FupfQ2kNGcE1LgprxKHcVWYQb86B-HozjHZcqtauBzFNV5tbTuB-TpkcvJfNcFLlH3b8mb-H_ox35FjqBSAjLKyoeqfKTpVjvXhd09knwgJf6VKq6UC418_TOljMVfFTWXUxlnfhOOnzW6HSSzD1c9WrCuVzsUMv54szidQ9wf1cYWf3g5qFDxDQKis99gcDaiCAwM3yEBIzuNeeCa5dartHDb1xEB_HcHSeYbghbMjGfasvKn0aZRsnTyC0xhWBlsolZE"",
    ""e"": ""AQAB"",
    ""d"": ""n7fzJc3_WG59VEOBTkayzuSMM780OJQuZjN_KbH8lOZG25ZoA7T4Bxcc0xQn5oZE5uSCIwg91oCt0JvxPcpmqzaJZg1nirjcWZ-oBtVk7gCAWq-B3qhfF3izlbkosrzjHajIcY33HBhsy4_WerrXg4MDNE4HYojy68TcxT2LYQRxUOCf5TtJXvM8olexlSGtVnQnDRutxEUCwiewfmmrfveEogLx9EA-KMgAjTiISXxqIXQhWUQX1G7v_mV_Hr2YuImYcNcHkRvp9E7ook0876DhkO8v4UOZLwA1OlUX98mkoqwc58A_Y2lBYbVx1_s5lpPsEqbbH-nqIjh1fL0gdNfihLxnclWtW7pCztLnImZAyeCWAG7ZIfv-Rn9fLIv9jZ6r7r-MSH9sqbuziHN2grGjD_jfRluMHa0l84fFKl6bcqN1JWxPVhzNZo01yDF-1LiQnqUYSepPf6X3a2SOdkqBRiquE6EvLuSYIDpJq3jDIsgoL8Mo1LoomgiJxUwL_GWEOGu28gplyzm-9Q0U0nyhEf1uhSR8aJAQWAiFImWH5W_IQT9I7-yrindr_2fWQ_i1UgMsGzA7aOGzZfPljRy6z-tY_KuBG00-28S_aWvjyUc-Alp8AUyKjBZ-7CWH32fGWK48j1t-zomrwjL_mnhsPbGs0c9WsWgRzI-K8gE"",
    ""p"": ""7_2v3OQZzlPFcHyYfLABQ3XP85Es4hCdwCkbDeltaUXgVy9l9etKghvM4hRkOvbb01kYVuLFmxIkCDtpi-zLCYAdXKrAK3PtSbtzld_XZ9nlsYa_QZWpXB_IrtFjVfdKUdMz94pHUhFGFj7nr6NNxfpiHSHWFE1zD_AC3mY46J961Y2LRnreVwAGNw53p07Db8yD_92pDa97vqcZOdgtybH9q6uma-RFNhO1AoiJhYZj69hjmMRXx-x56HO9cnXNbmzNSCFCKnQmn4GQLmRj9sfbZRqL94bbtE4_e0Zrpo8RNo8vxRLqQNwIy85fc6BRgBJomt8QdQvIgPgWCv5HoQ"",
    ""q"": ""zqOHk1P6WN_rHuM7ZF1cXH0x6RuOHq67WuHiSknqQeefGBA9PWs6ZyKQCO-O6mKXtcgE8_Q_hA2kMRcKOcvHil1hqMCNSXlflM7WPRPZu2qCDcqssd_uMbP-DqYthH_EzwL9KnYoH7JQFxxmcv5An8oXUtTwk4knKjkIYGRuUwfQTus0w1NfjFAyxOOiAQ37ussIcE6C6ZSsM3n41UlbJ7TCqewzVJaPJN5cxjySPZPD3Vp01a9YgAD6a3IIaKJdIxJS1ImnfPevSJQBE79-EXe2kSwVgOzvt-gsmM29QQ8veHy4uAqca5dZzMs7hkkHtw1z0jHV90epQJJlXXnH8Q"",
    ""dp"": ""19oDkBh1AXelMIxQFm2zZTqUhAzCIr4xNIGEPNoDt1jK83_FJA-xnx5kA7-1erdHdms_Ef67HsONNv5A60JaR7w8LHnDiBGnjdaUmmuO8XAxQJ_ia5mxjxNjS6E2yD44USo2JmHvzeeNczq25elqbTPLhUpGo1IZuG72FZQ5gTjXoTXC2-xtCDEUZfaUNh4IeAipfLugbpe0JAFlFfrTDAMUFpC3iXjxqzbEanflwPvj6V9iDSgjj8SozSM0dLtxvu0LIeIQAeEgT_yXcrKGmpKdSO08kLBx8VUjkbv_3Pn20Gyu2YEuwpFlM_H1NikuxJNKFGmnAq9LcnwwT0jvoQ"",
    ""dq"": ""S6p59KrlmzGzaQYQM3o0XfHCGvfqHLYjCO557HYQf72O9kLMCfd_1VBEqeD-1jjwELKDjck8kOBl5UvohK1oDfSP1DleAy-cnmL29DqWmhgwM1ip0CCNmkmsmDSlqkUXDi6sAaZuntyukyflI-qSQ3C_BafPyFaKrt1fgdyEwYa08pESKwwWisy7KnmoUvaJ3SaHmohFS78TJ25cfc10wZ9hQNOrIChZlkiOdFCtxDqdmCqNacnhgE3bZQjGp3n83ODSz9zwJcSUvODlXBPc2AycH6Ci5yjbxt4Ppox_5pjm6xnQkiPgj01GpsUssMmBN7iHVsrE7N2iznBNCeOUIQ"",
    ""qi"": ""FZhClBMywVVjnuUud-05qd5CYU0dK79akAgy9oX6RX6I3IIIPckCciRrokxglZn-omAY5CnCe4KdrnjFOT5YUZE7G_Pg44XgCXaarLQf4hl80oPEf6-jJ5Iy6wPRx7G2e8qLxnh9cOdf-kRqgOS3F48Ucvw3ma5V6KGMwQqWFeV31XtZ8l5cVI-I3NzBS7qltpUVgz2Ju021eyc7IlqgzR98qKONl27DuEES0aK0WE97jnsyO27Yp88Wa2RiBrEocM89QZI1seJiGDizHRUP4UZxw9zsXww46wy0P6f9grnYp7t8LkyDDk8eoI4KX6SNMNVcyVS9IWjlq8EzqZEKIA""
}
";
            string token =
                "eyJhbGciOiJSU0EtT0FFUCIsImtpZCI6InNhbXdpc2UuZ2FtZ2VlQGhvYmJpdG9uLmV4YW1wbGUiLCJlbmMiOiJBMjU2R0NNIn0.rT99rwrBTbTI7IJM8fU3Eli7226HEB7IchCxNuh7lCiud48LxeolRdtFF4nzQibeYOl5S_PJsAXZwSXtDePz9hk-BbtsTBqC2UsPOdwjC9NhNupNNu9uHIVftDyucvI6hvALeZ6OGnhNV4v1zx2k7O1D89mAzfw-_kT3tkuorpDU-CpBENfIHX1Q58-Aad3FzMuo3Fn9buEP2yXakLXYa15BUXQsupM4A1GD4_H4Bd7V3u9h8Gkg8BpxKdUV9ScfJQTcYm6eJEBz3aSwIaK4T3-dwWpuBOhROQXBosJzS1asnuHtVMt2pKIIfux5BC6huIvmY7kzV7W7aIUrpYm_3H4zYvyMeq5pGqFmW2k8zpO878TRlZx7pZfPYDSXZyS0CfKKkMozT_qiCwZTSz4duYnt8hS4Z9sGthXn9uDqd6wycMagnQfOTs_lycTWmY-aqWVDKhjYNRf03NiwRtb5BE-tOdFwCASQj3uuAgPGrO2AWBe38UjQb0lvXn1SpyvYZ3WFc7WOJYaTa7A8DRn6MC6T-xDmMuxC0G7S2rscw5lQQU06MvZTlFOt0UvfuKBa03cxA_nIBIhLMjY2kOTxQMmpDPTr6Cbo8aKaOnx6ASE5Jx9paBpnNmOOKH35j_QlrQhDWUN6A2Gg8iFayJ69xDEdHAVCGRzN3woEI2ozDRs.-nBoKLH0YkLZPSI9.o4k2cnGN8rSSw3IDo1YuySkqeS_t2m1GXklSgqBdpACm6UJuJowOHC5ytjqYgRL-I-soPlwqMUf4UgRWWeaOGNw6vGW-xyM01lTYxrXfVzIIaRdhYtEMRBvBWbEwP7ua1DRfvaOjgZv6Ifa3brcAM64d8p5lhhNcizPersuhw5f-pGYzseva-TUaL8iWnctc-sSwy7SQmRkfhDjwbz0fz6kFovEgj64X1I5s7E6GLp5fnbYGLa1QUiML7Cc2GxgvI7zqWo0YIEc7aCflLG1-8BboVWFdZKLK9vNoycrYHumwzKluLWEbSVmaPpOslY2n525DxDfWaVFUfKQxMF56vn4B9QMpWAbnypNimbM8zVOw.UCGiqJxhBI3IFVdPalHHvA";

            var js = new JavaScriptSerializer();
            var jwk = js.Deserialize<IDictionary<string, string>>(json);

            byte[] p = Base64Url.Decode(jwk["p"]);
            byte[] q = Base64Url.Decode(jwk["q"]);
            byte[] d = Base64Url.Decode(jwk["d"]);
            byte[] e = Base64Url.Decode(jwk["e"]);
            byte[] qi = Base64Url.Decode(jwk["qi"]);
            byte[] dq = Base64Url.Decode(jwk["dq"]);
            byte[] dp = Base64Url.Decode(jwk["dp"]);
            byte[] n = Base64Url.Decode(jwk["n"]);

            RSA key = RSA.Create();
            RSAParameters keyParams = new RSAParameters();
            keyParams.P = p;
            keyParams.Q = q;
            keyParams.D = d;
            keyParams.Exponent = e;
            keyParams.InverseQ = qi;
            keyParams.DP = dp;
            keyParams.DQ = dq;
            keyParams.Modulus = n;

            key.ImportParameters(keyParams);

            string payload = JWT.Decode(token, key);

            Console.Out.WriteLine(payload);
```

and it produces:
```
You can trust us to stick with you through thick and thin–to the bitter end. And you can trust us to keep any secret of yours–closer than you keep it yourself. But you cannot trust us to let you face trouble alone, and go off without a word. We are your friends, Frodo.
```

**Comment by Spomky** [comment]
Hi @dvsekhvalnov,

Many thanks! That's really kind of you.
I also successfully decrypted the token you issued in https://github.com/dvsekhvalnov/jose-jwt/issues/93#issuecomment-388352836 with the PKCS#12 key you shared. Hereafter the source code I wrote.

I really think that both libraries are compliant with the specification. From my understanding, it seems to be an issue caused by a wrong key conversion as mentioned by @z3nth10n.

<details>

```php
<?php

require_once 'vendor/autoload.php';

use Jose\Factory\JWKFactory;

$jwk = createFromPKCS12CertificateFile(__DIR__.'/signing-key.p12', '1');
dump($jwk);

$loader = new \Jose\Loader();
$input = 'eyJhbGciOiJSU0EtT0FFUCIsImVuYyI6IkEyNTZHQ00ifQ.GhYb6mJA8w2hTQ_ks4R_ygVJsD2j4fzS8uTVtp9UolL-NQZ1Jw6MYilsFiZ0k9OAUyHLjorDl7m0StojZZfJSyNjKgumLcWrGAhujiq9MDYFepjIv2CCtNgdIxTq2zyPUeKAXGCtooKd4XXnjf_zodR3JlATgvZjDg9pbF0Zda6thv6Mf7Zd5PdC4Ff9wSkd53zfioXACjUSSrkGjM5cU1YtQorlR-0ONpN837G4gZzjuYEZZFB_jeXUX--FRQHLZw5bGWx84ADM_hrgyYLz3f4S62Ws8VNpDndv3D1yGspem6H0Pa0Q9UQAycs844_TsfoML3MUIObQxnq3afTxBg.X5eSxt3Re5aWkHHL.GheNPfa_xKHK0fZOQK4.LXA6LEn-VnBy9VQ9eTz8vQ';

$jwe = $loader->loadAndDecryptUsingKey($input, $jwk, ['RSA-OAEP'], ['A256GCM'], $recipient);

dump($jwe);


function createFromPKCS12CertificateFile(string $file, ?string $secret = '', array $additional_values = []): \Jose\Object\JWK
{
    $res = openssl_pkcs12_read(file_get_contents($file), $certs, $secret);
    if (false === $res || !is_array($certs) || !array_key_exists('pkey', $certs)) {
        throw new \RuntimeException('Unable to load the certificates.');
    }
    return JWKFactory::createFromKey($certs['pkey'], null, $additional_values);
};
```
</details>

**Comment by dvsekhvalnov** [comment]
Yep, looks like it just keys :)

**Comment by z3nth10n** [comment]
Thanks!!!

A last question, I see that from X509Certificate you can generate a public key [x509.GetRSAPublicKey()](https://msdn.microsoft.com/en-us/library/system.security.cryptography.x509certificates.x509certificate.getpublickey%28v=vs.110%29.aspx?f=255&MSPPError=-2147217396) that this returns byte[] (so is perfect to transmit over the network).

But, which is the equivalent to it in PHP. Maybe using JWKFactory `toPublic()` method? I see this generates a JWKInterface object that I can convert to a Json array with `jsonSerialize()`.

I will test it. But I still don't know how I will read this public key encoded into json with C#. Because, I cannot send the p12 file (this is the private key).

@dvsekhvalnov can you help me? I don't find anyway to read this key from an object, maybe with a byte array?

Thanks again. 😃

**Comment by z3nth10n** [comment]
I'm on a security conference and I have realized about that sending public keys over the network is insecure due to MitM attacks. So I would prefer to generate a public key for each different version of the client, sign it and use any anti-tamper solution. I only have to ensure a method (with obfuscation) that checks on the server if my app has been modified to avoid its execution.

So with the methods you gave me, I think that I will capable to do a "secure" client.

Thanks!!

**Comment by Spomky** [comment]
This is right: the key exchange process is a critical step.
I recommend the following:

* Each party creates its private/public key pairs.
* The client sends its public key to the server. The public key can be encrypted using the public key of the server
* The server associates the public key of the client with the client data
* For each next data exchange, the parties sign the data using their private key and then encrypt with the public key of the other party.

Additional measures to be taken:
* Because the first key exchange is critical, the public key of the server may be built in the client.
* The signature key pair and the encryption key pair are not the same.
* Rotate the keys.

I wrote [some recommendations here](https://web-token.spomky-labs.com/security/).
Is there any available presentations regarding the conference you attended? I will be happy to update those recommendation with other security practices.

**Comment by z3nth10n** [comment]
"The server associates the public key of the client with the client data" I couldn't imagine this, can you explain this more in detail?

"The parties sign the data using their private key and then encrypt with the public key of the other party." Same here, what so you mean by signing? Because with private keys you only can decrypt... Explain please

And by rotating keys, what do you mean?

**Comment by z3nth10n** [comment]
Yesterday, I was on my mobile phone, so I couldn't investigate so much.

Now, I know what means [sign](https://github.com/Spomky-Labs/jose/blob/master/doc/operation/Sign.md) (I could imagine what did you mean, but I didn't look at this).

And rotating (but https://web-token.spomky-labs.com/security/ isn't available, I used Google cache and downloaded it), instead of rotating, I will keep a key for every version. Anyway is difficult to break a 4096 bits key, so I don't worry about rotation, I need a good implementation. Anyway I need your to explain an example of implementation.

But I still need an example of association of public key with the client data.
