### ISSUE TITLE
Accessing claim value in JWT

### ISSUE THREAD

**Issue by theminer3746** [Spomky-Labs/jose#332]
I'm thinking about using `getClaim()` method from `Jose\Object\JWTInterface` (just like when we're using it in `ClaimCheckerInterface`) to get value of that claim. But I can't figure out a way to load the JWT so I can do that.

Edit : I've just found a solution to my problem using the `JWTLoader` class. But when I check the time I check if the claims is valid and the time I actually want to use that claim is different. Is there a way to do this without requiring me to instantiate `JWTLoader`? Since to do that I'd have to instantiate `CheckManager` and `Verifier` too.

**Comment by Spomky** [comment]
The loader has to be instantiated. There is no static method.
Please note that this library will be deprecated in less than 6 months. You should consider the use of https://github.com/web-token instead.
