### ISSUE TITLE
can not install

### ISSUE THREAD

**Issue by langziyang** [Spomky-Labs/jose#333]
composer require spomky-labs/jose
Using version ^7.1 for spomky-labs/jose
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package spomky-labs/jose No version set (parsed as 1.0.0) is satisfiable by spomky-labs/jose[No version set (parsed as 1.0.0)] but these conflict with your requirements or minimum-stability.
  Problem 2
    - Installation request for mdanter/ecc 0.5.* -> satisfiable by mdanter/ecc[v0.5.0].
    - mdanter/ecc v0.5.0 requires ext-gmp * -> the requested PHP extension gmp is missing from your system.
  Problem 3
    - mdanter/ecc v0.5.0 requires ext-gmp * -> the requested PHP extension gmp is missing from your system.
    - spomky-labs/jose v7.1.0 requires mdanter/ecc 0.5.* -> satisfiable by mdanter/ecc[v0.5.0].
    - Installation request for spomky-labs/jose ^7.1 -> satisfiable by spomky-labs/jose[v7.1.0].

  To enable extensions, verify that they are enabled in your .ini files:
    - /usr/local/php/etc/php.ini
    - /usr/local/php/etc/php.d/03-imagick.ini
    - /usr/local/php/etc/php.d/04-fileinfo.ini
    - /usr/local/php/etc/php.d/05-memcache.ini
    - /usr/local/php/etc/php.d/05-memcached.ini
  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.

Installation failed, reverting ./composer.json to its original content.

**Comment by Spomky** [comment]
It looks like the extension GMP is not installed and causes the failure.

This library will be deprecated by the end of the year in favor of [web-token/jwt-framework](https://github.com/web-token/jwt-framework). If you start a new project, you should install the later.

**Comment by langziyang** [comment]
i fix gmp extension,now just have one error,and i want use this project
 Problem 1
    - The requested package spomky-labs/jose No version set (parsed as 1.0.0) is satisfiable by spomky-labs/jose[No version set (parsed as 1.0.0)] but these conflict with your requirements or minimum-stability.

**Comment by Spomky** [comment]
You should specify what version you want to install. `v1.0.0` is pretty old. Last release is ^7.1 

```sh
composer require spomky-labs/jose:^7.1
```

**Comment by Spomky** [comment]
What is your PHP version?

**Comment by langziyang** [comment]
> What is your PHP version?

7.1.22

**Comment by Spomky** [comment]
What are the exact error lines when calling `composer require spomky-labs/jose:^7.1`?

**Comment by langziyang** [comment]
> What are the exact error lines when calling `composer require spomky-labs/jose:^7.1`?

composer require spomky-labs/jose:^7.1
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package spomky-labs/jose No version set (parsed as 1.0.0) is satisfiable by spomky-labs/jose[No version set (parsed as 1.0.0)] but these conflict with your requirements or minimum-stability.


Installation failed, reverting ./composer.json to its original content.

**Comment by Spomky** [comment]
As far as I understand, it is trying to install v1.0.0, not ^7.1.
Can you copy/paste your composer.json content?

**Comment by langziyang** [comment]
cat composer.json 
{
    "name": "spomky-labs/jose",
    "description": "JSON Object Signing and Encryption library for PHP.",
    "type": "library",
    "license": "MIT",
    "keywords": ["JWS", "JWT", "JWE", "JWA", "JWK", "JWKSet", "Jot", "Jose", "RFC7515", "RFC7516", "RFC7517", "RFC7518", "RFC7519", "RFC7520"],
    "homepage": "https://github.com/Spomky-Labs/Jose",
    "authors": [
        {
            "name": "Florent Morselli",
            "homepage": "https://github.com/Spomky"
        },{
            "name": "All contributors",
            "homepage": "https://github.com/Spomky-Labs/jose/contributors"
        }
    ],
    "autoload": {
        "psr-4": {
            "Jose\\":  "src/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "Jose\\Test\\":  "tests/"
        }
    },
    "require": {
        "php": "^7.0",
        "ext-gmp": "*",
        "lib-openssl": "*",
        "spomky-labs/base64url": "^1.0",
        "spomky-labs/aes-key-wrap": "^3.0|^4.0",
        "spomky-labs/php-aes-gcm": "^1.2",
        "beberlei/assert": "^2.4",
        "symfony/polyfill-mbstring": "^1.1",
        "fgrosse/phpasn1": "^2.0",
        "mdanter/ecc": "0.5.*",
        "psr/cache": "^1.0",
        "spomky-labs/jose": "^1"
    },
    "require-dev": {
        "phpunit/phpunit": "^6.0",
        "satooshi/php-coveralls": "^2.0",
        "symfony/cache": "^2.0|^3.0|^4.0"
    },
   "suggest":{
        "ext-crypto": "Highly recommended when you use AES GCM based algorithms.",
        "ext-ed25519": "For EdDSA with Ed25519 curves support.",
        "ext-curve25519": "For EdDSA with X25519 curves support.",
        "ext-curl": "Needed by the JKU/X5U keyset factory."
   },
    "extra": {
        "branch-alias": {
            "dev-master": "7.1.x-dev"
        }
    }
}

**Comment by Spomky** [comment]
Replace `"spomky-labs/jose": "^1"` with `"spomky-labs/jose": "^7.1"` and call `composer update`

**Comment by langziyang** [comment]
same error,i can composer use ^1

**Comment by Spomky** [comment]
What I don't understand is that you copy/paste the composer.json file from this library, not the one of your application.
It looks like you downloaded the whole library and trying to work in its root folder.
You should create an empty folder, initialize composer and install the library.

```sh
mkdir project
cd project
composer init
```

Follow the interactive steps and just add "spomky-labs/jose" as dependency.

**Comment by langziyang** [comment]
my bad,I rarely use composer,work now,thanks

**Comment by Spomky** [comment]
:+1: Your welcome, Closing then.
