### ISSUE TITLE
Deprecated filter_var()

### ISSUE THREAD

**Issue by devgowa** [Spomky-Labs/jose#335]
`filter_var(): explicit use of FILTER_FLAG_SCHEME_REQUIRED and FILTER_FLAG_HOST_REQUIRED is deprecated in DownloadedJWKSet.php line 65`

**PHP 7.3.1 (cli) (built: Jan 10 2019 13:15:37) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.1, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.1, Copyright (c) 1999-2018, by Zend Technologies**

Thank's.

**Comment by Spomky** [comment]
This library is not maintained anymore except regarding security issues.
Please use [`web-token/jwt-framework`](https://github.com/web-token/jwt-framework) or another implementation.

Thanks
