### ISSUE TITLE
Use OpenSSL instead of pure PHP implemention for ECDSA signatures if possible

### ISSUE THREAD

**Issue by Spomky** [Spomky-Labs/jose#88]

**Comment by afk11** [comment]
Just dropping by, I wanted to mention the newer PHPECC could be running about 66% faster than before! https://gist.github.com/afk11/4208b0fa895055ca2a226c856de4f112

**Comment by Spomky** [comment]
Hi @afk11 and thank you for noticing me the last news on your library.
I ran again the performance tests written for this library and I confirm you they are running faster.

[On this page](https://github.com/Spomky-Labs/jose/blob/master/doc/Performance.md) you will see, for example, that signature operations take from 119 to 316 ms per signature and 335 to 895 ms per verification.
Now it is between 34 and 75 ms per signature and 56 and 143 ms per verification so
* ~72% faster for signature operations
* ~85% faster for verification operations

Thank you for all these efforts!
When you will release a new stable version, I will update this library to integrate it as a dependency and not just a suggestion.

**Comment by Spomky** [comment]
Done.
The library now uses OpenSSL if possible. Else, the PHPECC library is used as a backup.

**Comment by afk11** [comment]
Sorry, I saw this but didn't get to respond at the time. Nice on the benchmarks; it's better than what I was seeing :)

awesome stuff!
